"""Pydantic schemas for delivery callbacks and dispatch requests."""

import datetime

from pydantic import BaseModel


class RecipientInfo(BaseModel):
    """Customer info embedded in a dispatch request."""

    customer_id: int
    name: str
    email: str


class DispatchRequest(BaseModel):
    """Payload sent by the CRM to the channel service for each message."""

    dispatch_id: str          # UUID generated by CRM; idempotency key
    campaign_id: int
    message_id: int
    recipient: RecipientInfo
    message_body: str
    channel: str = "email"
    callback_url: str         # Full URL of CRM's callback endpoint


class DispatchResponse(BaseModel):
    """Immediate 202 response from the channel service."""

    accepted: bool
    dispatch_id: str


class CallbackEvent(BaseModel):
    """Delivery event POSTed by the channel service to the CRM callback endpoint."""

    event_id: str             # Channel-service UUID — UNIQUE in delivery_events
    dispatch_id: str          # Matches the original dispatch_id
    campaign_id: int
    message_id: int           # Maps to campaign_messages.id
    customer_id: int
    status: str               # sent | delivered | opened | clicked | failed
    timestamp: datetime.datetime
    is_retry: bool = False
    is_final: bool = False


class CallbackResponse(BaseModel):
    """CRM's acknowledgement of a received callback event."""

    received: bool
    event_id: str
