"""update_orders_and_delivery_status

Revision ID: 250faeb196cb
Revises: 4fdb765d18ff
Create Date: 2026-06-12 18:41:23.970367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250faeb196cb'
down_revision: Union[str, Sequence[str], None] = '4fdb765d18ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('items', sa.JSON(), nullable=False))
    op.add_column('orders', sa.Column('source_channel', sa.String(length=50), nullable=False))
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'coffee_blend')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###

    # Drop old check constraint and add updated check constraint
    op.drop_constraint('ck_delivery_events_status', 'delivery_events', type_='check')
    op.create_check_constraint(
        'ck_delivery_events_status',
        'delivery_events',
        "status IN ('sent', 'delivered', 'opened', 'clicked', 'failed', 'purchased')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('coffee_blend', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('orders', 'source_channel')
    op.drop_column('orders', 'items')
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###

    # Restore old check constraint
    op.drop_constraint('ck_delivery_events_status', 'delivery_events', type_='check')
    op.create_check_constraint(
        'ck_delivery_events_status',
        'delivery_events',
        "status IN ('sent', 'delivered', 'opened', 'clicked', 'failed')"
    )
