"""add_orders_and_final_status

Revision ID: 4fdb765d18ff
Revises: 3824f4b6a65c
Create Date: 2026-06-12 16:45:27.861866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fdb765d18ff'
down_revision: Union[str, Sequence[str], None] = '3824f4b6a65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coffee_blend', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.alter_column('campaign_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('campaign_messages_campaign_id_idx'), table_name='campaign_messages')
    op.create_index(op.f('ix_campaign_messages_campaign_id'), 'campaign_messages', ['campaign_id'], unique=False)
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'state_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('customers_email_idx'), table_name='customers')
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.add_column('delivery_events', sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('delivery_events', 'event_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Channel-service-assigned UUID; UNIQUE constraint enforces idempotency',
               existing_nullable=False)
    op.alter_column('delivery_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('delivery_events_event_id_idx'), table_name='delivery_events')
    op.drop_constraint(op.f('delivery_events_event_id_key'), 'delivery_events', type_='unique')
    op.drop_index(op.f('delivery_events_message_id_idx'), table_name='delivery_events')
    op.create_index(op.f('ix_delivery_events_campaign_message_id'), 'delivery_events', ['campaign_message_id'], unique=False)
    op.create_index(op.f('ix_delivery_events_event_id'), 'delivery_events', ['event_id'], unique=True)
    op.alter_column('segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('segments_campaign_id_idx'), table_name='segments')
    op.create_index(op.f('ix_segments_campaign_id'), 'segments', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_campaign_id'), table_name='segments')
    op.create_index(op.f('segments_campaign_id_idx'), 'segments', ['campaign_id'], unique=False)
    op.alter_column('segments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_delivery_events_event_id'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_campaign_message_id'), table_name='delivery_events')
    op.create_index(op.f('delivery_events_message_id_idx'), 'delivery_events', ['campaign_message_id'], unique=False)
    op.create_unique_constraint(op.f('delivery_events_event_id_key'), 'delivery_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('delivery_events_event_id_idx'), 'delivery_events', ['event_id'], unique=True)
    op.alter_column('delivery_events', 'received_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_events', 'event_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Channel-service-assigned UUID; UNIQUE constraint enforces idempotency',
               existing_nullable=False)
    op.drop_column('delivery_events', 'is_final')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('customers_email_idx'), 'customers', ['email'], unique=True)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'state_updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_campaign_messages_campaign_id'), table_name='campaign_messages')
    op.create_index(op.f('campaign_messages_campaign_id_idx'), 'campaign_messages', ['campaign_id'], unique=False)
    op.alter_column('campaign_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
