"""add_audience_id_to_campaigns

Revision ID: 73b9cb31fd46
Revises: ed10177259b8
Create Date: 2026-06-14 11:32:42.079467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b9cb31fd46'
down_revision: Union[str, Sequence[str], None] = 'ed10177259b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('audience_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaigns_audience_id'), 'campaigns', ['audience_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'audiences', ['audience_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_audience_id'), table_name='campaigns')
    op.drop_column('campaigns', 'audience_id')
    # ### end Alembic commands ###
