"""add_multi_tenant_rls

Revision ID: 87b8ebdc18f4
Revises: 250faeb196cb
Create Date: 2026-06-12 21:39:54.015703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87b8ebdc18f4'
down_revision: Union[str, Sequence[str], None] = '250faeb196cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create tenants table
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # 2. Insert default tenant (BrewMate) so existing records have a valid association
    op.execute("INSERT INTO tenants (id, name, created_at) VALUES (1, 'BrewMate', NOW()) ON CONFLICT (name) DO NOTHING")

    # 3. Create crm_fields table
    op.create_table('crm_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('allowed_enums', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'field_name', name='uq_crm_fields_tenant_entity_field')
    )
    op.create_index(op.f('ix_crm_fields_tenant_id'), 'crm_fields', ['tenant_id'], unique=False)
    
    # 4. Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)

    # 5. Add tenant_id column as nullable to existing tables
    tables_to_migrate = [
        'campaign_messages',
        'campaigns',
        'customers',
        'delivery_events',
        'orders',
        'segment_customers',
        'segments'
    ]
    for table in tables_to_migrate:
        op.add_column(table, sa.Column('tenant_id', sa.Integer(), nullable=True))

    # 6. Update existing rows to use the default tenant ID (1)
    for table in tables_to_migrate:
        op.execute(f"UPDATE {table} SET tenant_id = 1 WHERE tenant_id IS NULL")

    # 7. Alter columns to be nullable=False
    for table in tables_to_migrate:
        op.alter_column(table, 'tenant_id', nullable=False)

    # 8. Create constraints, indexes and FKs on existing tables
    op.create_index(op.f('ix_campaign_messages_tenant_id'), 'campaign_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('customers', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_customers_tenant_email', 'customers', ['tenant_id', 'email'])
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_delivery_events_tenant_id'), 'delivery_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'delivery_events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_segment_customers_tenant_id'), 'segment_customers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'segment_customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_segments_tenant_id'), 'segments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'segments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    # 9. Enable RLS and Force RLS on all shared tables
    shared_tables = [
        'users',
        'crm_fields',
        'customers',
        'orders',
        'campaigns',
        'campaign_messages',
        'delivery_events',
        'segments',
        'segment_customers'
    ]
    for table in shared_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::integer)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    shared_tables = [
        'users',
        'crm_fields',
        'customers',
        'orders',
        'campaigns',
        'campaign_messages',
        'delivery_events',
        'segments',
        'segment_customers'
    ]
    for table in shared_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.drop_constraint(None, 'segments', type_='foreignkey')
    op.drop_index(op.f('ix_segments_tenant_id'), table_name='segments')
    op.drop_column('segments', 'tenant_id')
    op.drop_constraint(None, 'segment_customers', type_='foreignkey')
    op.drop_index(op.f('ix_segment_customers_tenant_id'), table_name='segment_customers')
    op.drop_column('segment_customers', 'tenant_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_column('orders', 'tenant_id')
    op.drop_constraint(None, 'delivery_events', type_='foreignkey')
    op.drop_index(op.f('ix_delivery_events_tenant_id'), table_name='delivery_events')
    op.drop_column('delivery_events', 'tenant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint('uq_customers_tenant_email', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_column('customers', 'metadata')
    op.drop_column('customers', 'tenant_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_column('campaigns', 'tenant_id')
    op.drop_constraint(None, 'campaign_messages', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_messages_tenant_id'), table_name='campaign_messages')
    op.drop_column('campaign_messages', 'tenant_id')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crm_fields_tenant_id'), table_name='crm_fields')
    op.drop_table('crm_fields')
    op.drop_table('tenants')
    # ### end Alembic commands ###
