"""add_stats_health_attribution_scheduling

Revision ID: ccce3e8020a0
Revises: cd91f93954c3
Create Date: 2026-06-13 23:18:59.509445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccce3e8020a0'
down_revision: Union[str, Sequence[str], None] = 'cd91f93954c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('opened_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicked_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchased_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attributed_revenue', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_stats_campaign_id'), 'campaign_stats', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_campaign_stats_tenant_id'), 'campaign_stats', ['tenant_id'], unique=False)
    op.create_table('customer_health_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recency_score', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('spend_score', sa.Integer(), nullable=False),
    sa.Column('frequency_score', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("zone IN ('healthy', 'at_risk', 'churning')", name='ck_health_zone_valid'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_health_score_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_health_scores_customer_id'), 'customer_health_scores', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_health_scores_tenant_id'), 'customer_health_scores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_health_scores_zone'), 'customer_health_scores', ['zone'], unique=False)
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='When this campaign should auto-dispatch; NULL = manual dispatch'))
    op.add_column('campaigns', sa.Column('channel', sa.String(length=20), server_default='sms', nullable=False, comment='Channel type: sms, whatsapp, email, rcs'))
    op.add_column('orders', sa.Column('communication_id', sa.Integer(), nullable=True, comment='Links to originating campaign message for revenue attribution; NULL for organic orders'))
    op.create_index(op.f('ix_orders_communication_id'), 'orders', ['communication_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'campaign_messages', ['communication_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_communication_id'), table_name='orders')
    op.drop_column('orders', 'communication_id')
    op.drop_column('campaigns', 'channel')
    op.drop_column('campaigns', 'scheduled_at')
    op.drop_index(op.f('ix_customer_health_scores_zone'), table_name='customer_health_scores')
    op.drop_index(op.f('ix_customer_health_scores_tenant_id'), table_name='customer_health_scores')
    op.drop_index(op.f('ix_customer_health_scores_customer_id'), table_name='customer_health_scores')
    op.drop_table('customer_health_scores')
    op.drop_index(op.f('ix_campaign_stats_tenant_id'), table_name='campaign_stats')
    op.drop_index(op.f('ix_campaign_stats_campaign_id'), table_name='campaign_stats')
    op.drop_table('campaign_stats')
    # ### end Alembic commands ###
