"""add_dispatch_id_and_read_status

Revision ID: cd91f93954c3
Revises: 87b8ebdc18f4
Create Date: 2026-06-13 16:19:26.677430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd91f93954c3'
down_revision: Union[str, Sequence[str], None] = '87b8ebdc18f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_events', sa.Column('dispatch_id', sa.String(length=128), nullable=True, comment='Matches the original dispatch_id from channel service'))
    op.create_index(op.f('ix_delivery_events_dispatch_id'), 'delivery_events', ['dispatch_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("ALTER TABLE delivery_events DROP CONSTRAINT IF EXISTS ck_delivery_events_status")
    op.create_check_constraint(
        'ck_delivery_events_status',
        'delivery_events',
        "status IN ('sent', 'delivered', 'opened', 'read', 'clicked', 'failed', 'purchased')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE delivery_events DROP CONSTRAINT IF EXISTS ck_delivery_events_status")
    op.create_check_constraint(
        'ck_delivery_events_status',
        'delivery_events',
        "status IN ('sent', 'delivered', 'opened', 'clicked', 'failed', 'purchased')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_events_dispatch_id'), table_name='delivery_events')
    op.drop_column('delivery_events', 'dispatch_id')
    # ### end Alembic commands ###
