"""create_audiences

Revision ID: ed10177259b8
Revises: 7483ab7ff0ee
Create Date: 2026-06-14 11:26:47.846425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed10177259b8'
down_revision: Union[str, Sequence[str], None] = '7483ab7ff0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('filter_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiences_tenant_id'), 'audiences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("ALTER TABLE audiences ENABLE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY audience_tenant_isolation ON audiences
        FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::integer);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS audience_tenant_isolation ON audiences;")
    op.execute("ALTER TABLE audiences DISABLE ROW LEVEL SECURITY;")
    op.drop_index(op.f('ix_audiences_tenant_id'), table_name='audiences')
    op.drop_table('audiences')
    # ### end Alembic commands ###
